# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161221_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='image',
            field=models.CharField(default='http://127.0.0.1:8080/heroku.jpg', max_length=250),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.CharField(default='http://127.0.0.1:8080/heroku.jpg', max_length=250),
        ),
    ]
